package tech.gruppone.stalker.app.model.fragment;

import android.database.CursorIndexOutOfBoundsException;
import com.android.volley.Response;
import com.android.volley.Response.ErrorListener;
import com.android.volley.VolleyError;
import com.google.gson.Gson;
import tech.gruppone.stalker.app.business.HistoryResponse;
import tech.gruppone.stalker.app.business.UserHistory;
import tech.gruppone.stalker.app.utility.CurrentSessionSingleton;
import tech.gruppone.stalker.app.utility.WebSingleton;

public class ReportModel {

  public void getUsersHistory(int id) {
    WebSingleton.getInstance()
        .getUserHistory(
          id,
          jsonObject -> {
            HistoryResponse historyResponse = new Gson()
              .fromJson(jsonObject.toString(), HistoryResponse.class);
            //UserHistory userHistory = new UserHistory(jsonObject);
            CurrentSessionSingleton.getInstance().setHistoryResponse(historyResponse);

          },
          new ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {
              String str = "{\n"
                + "\n"
                + "  \"history\": [\n"
                + "\n"
                + "    {\n"
                + "\n"
                + "      \"organizationId\": 8265105042836091000,\n"
                + "\n"
                + "      \"historyPerOrganization\": {\n"
                + "\n"
                + "        \"userId\": 3080044179241892000,\n"
                + "\n"
                + "        \"history\": [\n"
                + "\n"
                + "          {\n"
                + "\n"
                + "            \"timestamp\": 9102832488246850000,\n"
                + "\n"
                + "            \"placeId\": 5088208673330754000,\n"
                + "\n"
                + "            \"inside\": false\n"
                + "\n"
                + "          },\n"
                + "\n"
                + "          {\n"
                + "\n"
                + "            \"timestamp\": -3723280794754423000,\n"
                + "\n"
                + "            \"placeId\": 1678397752427516000,\n"
                + "\n"
                + "            \"inside\": false\n"
                + "\n"
                + "          },\n"
                + "\n"
                + "          {\n"
                + "\n"
                + "            \"timestamp\": 1135573593078429700,\n"
                + "\n"
                + "            \"placeId\": 3930530116925470700,\n"
                + "\n"
                + "            \"inside\": false\n"
                + "\n"
                + "          }\n"
                + "\n"
                + "        ]\n"
                + "\n"
                + "      }\n"
                + "\n"
                + "    },\n"
                + "\n"
                + "    {\n"
                + "\n"
                + "      \"organizationId\": 8125625204117311000,\n"
                + "\n"
                + "      \"historyPerOrganization\": {\n"
                + "\n"
                + "        \"userId\": -8249447854119498000,\n"
                + "\n"
                + "        \"history\": [\n"
                + "\n"
                + "          {\n"
                + "\n"
                + "            \"timestamp\": -6592671895058663000,\n"
                + "\n"
                + "            \"placeId\": -4607788178351554600,\n"
                + "\n"
                + "            \"inside\": true\n"
                + "\n"
                + "          },\n"
                + "\n"
                + "          {\n"
                + "\n"
                + "            \"timestamp\": 5049340021195459000,\n"
                + "\n"
                + "            \"placeId\": -3701575241782233000,\n"
                + "\n"
                + "            \"inside\": true\n"
                + "\n"
                + "          },\n"
                + "\n"
                + "          {\n"
                + "\n"
                + "            \"timestamp\": -2151273955358097400,\n"
                + "\n"
                + "            \"placeId\": -413705611946639360,\n"
                + "\n"
                + "            \"inside\": false\n"
                + "\n"
                + "          },\n"
                + "\n"
                + "          {\n"
                + "\n"
                + "            \"timestamp\": 7785007612948179000,\n"
                + "\n"
                + "            \"placeId\": -6163623268519272000,\n"
                + "\n"
                + "            \"inside\": true\n"
                + "\n"
                + "          }\n"
                + "\n"
                + "        ]\n"
                + "\n"
                + "      }\n"
                + "\n"
                + "    },\n"
                + "\n"
                + "    {\n"
                + "\n"
                + "      \"organizationId\": -1530020443029078000,\n"
                + "\n"
                + "      \"historyPerOrganization\": {\n"
                + "\n"
                + "        \"userId\": 3063272852126257000,\n"
                + "\n"
                + "        \"history\": [\n"
                + "\n"
                + "          {\n"
                + "\n"
                + "            \"timestamp\": 7331499424853045000,\n"
                + "\n"
                + "            \"placeId\": -4358379891698536400,\n"
                + "\n"
                + "            \"inside\": false\n"
                + "\n"
                + "          }\n"
                + "\n"
                + "        ]\n"
                + "\n"
                + "      }\n"
                + "\n"
                + "    },\n"
                + "\n"
                + "    {\n"
                + "\n"
                + "      \"organizationId\": 9014511794800769000,\n"
                + "\n"
                + "      \"historyPerOrganization\": {\n"
                + "\n"
                + "        \"userId\": -2859962100280234000,\n"
                + "\n"
                + "        \"history\": [\n"
                + "\n"
                + "          {\n"
                + "\n"
                + "            \"timestamp\": -5901520753598654000,\n"
                + "\n"
                + "            \"placeId\": 6413935826498646000,\n"
                + "\n"
                + "            \"inside\": true\n"
                + "\n"
                + "          },\n"
                + "\n"
                + "          {\n"
                + "\n"
                + "            \"timestamp\": -739283794621091800,\n"
                + "\n"
                + "            \"placeId\": 6176788404657611000,\n"
                + "\n"
                + "            \"inside\": false\n"
                + "\n"
                + "          },\n"
                + "\n"
                + "          {\n"
                + "\n"
                + "            \"timestamp\": -7966694241836200000,\n"
                + "\n"
                + "            \"placeId\": -7977716376776677000,\n"
                + "\n"
                + "            \"inside\": false\n"
                + "\n"
                + "          },\n"
                + "\n"
                + "          {\n"
                + "\n"
                + "            \"timestamp\": -6441245646294143000,\n"
                + "\n"
                + "            \"placeId\": -8884784219617772000,\n"
                + "\n"
                + "            \"inside\": true\n"
                + "\n"
                + "          }\n"
                + "\n"
                + "        ]\n"
                + "\n"
                + "      }\n"
                + "\n"
                + "    }\n"
                + "\n"
                + "  ]\n"
                + "\n"
                + "}";
              HistoryResponse historyResponse = new Gson()
                .fromJson(str, HistoryResponse.class);
              //UserHistory userHistory = new UserHistory(jsonObject);
              CurrentSessionSingleton.getInstance().setHistoryResponse(historyResponse);
            }
          });
  }
}
