name: Documentation

on:
  pull_request:
  # push:
  #   branches:
  #     - '!master'

# TODO add PlantUML job
# TODO add spellcheck job: https://github.com/marketplace/actions/spellcheck-action
jobs:
  lint-markdown:
    name: Lint *.md
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
          ignore_files: 'CHANGELOG.md'
