name: Dynamic analysis and testing

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run gradle check
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Fetch master too
        run: |
          git fetch --no-tags --prune origin master

      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Gradle wrapper
        run: ./gradlew --console=plain --warning-mode=all

      - name: Run gradle check
        # no need to run spotlessCheck here.
        run: ./gradlew --console=plain --warning-mode=all --continue check -x spotlessCheck

      - name: Upload results to SonarCloud
        if: always()
        # exclude dependent tasks that were already executed during "Run gradle check" step
        run: |
          ./gradlew \
            --console=plain \
            --warning-mode=all \
            --info \
            sonarqube \
#            -x :app:compileDebugAndroidTestJavaWithJavac \
#            -x :app:compileDebugUnitTestJavaWithJavac \
            -Dsonar.login=${{ secrets.SONARCLOUD_LOGIN }} \
            -Dsonar.pullrequest.key=${{ github.event.number }} \
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
