name: Project management

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

  push:
    branches-ignore:
      - master

env:
  MY_GITHUB_TOKEN: ${{ secrets.ERCLU_ORGANIZATION_TOKEN }}

jobs:
  assign-main-project:
    name: Assign to our main project board
    runs-on: ubuntu-18.04

    if: github.event_name != 'push'

    steps:
      - name: Assign new issues and new PRs to the main organization project board
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: github.event.action == 'opened' && !contains(github.event.issue.labels.*.name, 'requirement')
        with:
          project: "https://github.com/orgs/GruppOne/projects/9"
          column_name: "To do"

  assign-requirement-main-project:
    name: Assign a requirement to our main project board
    runs-on: ubuntu-18.04

    if: github.event_name != 'push'

    steps:
      - name: Assign new requirement to the correct project column
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: contains(github.event.issue.labels.*.name, 'requirement')
        with:
          project: "https://github.com/orgs/GruppOne/projects/9"
          column_name: "To do - Requirements"
